spring:
    application:
        name: demokafka
    kafka:
        consumer:
            auto-offset-reset: earliest
    datasource:
        url: jdbc:postgresql://localhost:5432/test
        username: postgres
        password: Huykenzj994
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show-sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
                # Ensure proper datetime handling
                jdbc:
                    time_zone: UTC
                # Configure datetime precision
                types:
                    datetime:
                        precision: 6  # microseconds precision
#                use_sql_comments: true
#                hbm2ddl:
#                    auto: none
#                    schema_generation:
#                        scripts:
#                            action: create
##                            create-target: src/main/resources/db/migration/V2__add_users_table.sql
#                            create-target: target/generated-sql/V2__add_users_table.sql
    # Jackson configuration for better datetime handling
    jackson:
        serialization:
            write-dates-as-timestamps: false
        deserialization:
            fail-on-unknown-properties: false
            adjust-dates-to-context-time-zone: false
        time-zone: Asia/Ho_Chi_Minh
    flyway:
        enabled: true
#        baseline-on-migrate: true
        locations: classpath:db/migration
        schemas: public
        table: flyway_schema_history

# Logging configuration for debugging
logging:
    level:
        com.springkafka.demokafka.util.EntityDtoConverter: DEBUG
        com.springkafka.demokafka.config.JacksonConfig: DEBUG
        com.springkafka.demokafka.service.impl.UserService: DEBUG
        org.springframework.web: DEBUG
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

